<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">

            <div class="row-fluid actions">

                <input type="text" class="search span12" placeholder="O que deseja buscar?" />

            </div>	
            <?php include_once 'menu.phtml'; ?>
            
        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">

            <div class="row-fluid">

                <div class="box span8" ontablet="span12" ondesktop="span8">
                    <div class="box-header">
                        <h2>COMUNICADO</h2>
                    </div>
                    <div class="box-content" style="height:308px">
                        <div class="span12" style="height:308px"> Chegou o Vale-Cultura. Um benefício que pode chegar &agrave;s mãos de 42 milh&otilde;es de trabalhadores brasileiros. O cartão magnético pré-pago, válido em todo territ&oacute;rio nacional,  no valor de 50 reais mensais, vai possibilitar ao trabalhador de carteira assinada ir ao teatro, cinema, museus, espetáculos, shows, circo ou mesmo comprar ou alugar CDs, DVDs, livros, revistas e jornais. E para aqueles que quiserem comprar um instrumento musical ou mesmo fazer um programa cultural com um custo mais elevado, uma boa notícia: o crédito é cumulativo e não tem validade. é s&oacute; poupar por alguns meses e adquirir o bem cultural que desejar. O Vale também pode ser usado para fazer cursos de artes, audiovisual, dança, circo, fotografia, música, literatura ou teatro.<br><br>

Com o intuito de que o benefício chegue em primeira mão aos trabalhadores de baixa e média renda, a regra é clara: as empresas t&ecirc;m de oferecer o Vale-Cultura prioritariamente aos trabalhadores que recebem até 5 salários mínimos. Mas se a empresa quiser também pode oferecer o benefício para todo o quadro de funcionários, sempre respeitando a exig&ecirc;ncia de ofertar o benefício primeiramente ao trabalhador com menor salário.<br><br>

As empresas que desejam oferecer o benefício aos seus funcionários já podem se habilitar no sistema de credenciamento que estará disponível no site do Ministério da Cultura. Neste momento, a empresa deverá indicar a operadora que quer trabalhar.<br><br>

São as operadoras que vão produzir e distribuir os cart&otilde;es. São elas também que habilitarão os estabelecimentos que quiserem aceitar o Vale-Cultura. A taxa de administração cobrada pela operadora aos comerciantes será de no máximo 6%.<br><br></div>
                    </div>	
                </div>
            </div>
        </div>
        <!-- end: Content -->

    </div><!--/fluid-row-->


</div>